Repository rgehan/hacktoberfest-2k18-katas, pull requests merged in 2018-10, with the labels that each got.

#46 implement chunk
  src/chunk.js
  src/difference.js
  src/difference.test.js
Labels: missing new tests

#53 Implement fibonacci function
  src/fibonacci.js
  src/isSuffix.js
  src/isSuffix.test.js
Labels: missing new tests

#41 Added case for Min, and test suites.
  src/min.js
  src/min.test.js
  src/multiply.js
  src/pinValidator.js
  src/pinValidator.test.js
Labels: missing new tests, need to be fixed

#91 implement #77 ifZero and add isOdd
  src/ifzero.js
  src/isOdd.js
  src/isOdd.test.js
Labels: need to be fixed

#88 Implement 'firstCharacterInString'
  src/firstCharacterInString.js
  src/isCorrectBracketSequence.js
  src/isCorrectBracketSequence.test.js
Labels: missing new kata

#70 Completed isPalindrome challenge and added sorting challenge
  src/isPalindrome.js
  src/sort.test.js
Labels: need to be fixed

#96 Implement removeConsecutiveDuplicates (fix #45)
  src/addKeyAndValueToObject.js
  src/addKeyAndValueToObject.test.js
  src/removeConsecutiveDuplicates.js
Labels: missing new kata

#192 Complete the generateSquare kata and add a new one.
  src/generateSquare.js
  src/wordSpiral.js
  src/wordSpiral.test.js
Labels: action needed

#227 Implement sumOfPairs #163
  src/oddOccurrencesInArray.js
  src/oddOccurrencesInArray.test.js
  src/sumOfPairs.js
Labels: action needed

#231 Implement slug function (and fixed slug tests), added isTruthy tests
  src/isTruthy.js
  src/isTruthy.test.js
  src/slug.js
  src/slug.test.js
Labels: action needed

#229 Implemented isObject module
  src/contains.js
  src/contains.test.js
  src/isObject.js
Labels: action needed

#234 Implement isPrimeNumber. Add reverseArray function with unit tests
  src/isPrimeNumber.js
  src/reverseArray.js
  src/reverseArray.test.js
Labels: action needed

#418 Implementing linearSearch (also corrected misplaced parenthesis in un…
  src/linearSearch.js
  src/linearSearch.test.js
  src/wordCount.js
  src/wordCount.test.js
Labels: action needed

#556 Solve twitter block message generator challenge
  src/christmasTree.js
  src/christmasTree.test.js
  src/twitterBlockMessageGenerator.js
  src/twitterBlockMessageGenerator.test.js
Labels: action needed

#574 implement capitalizedWordCounter
  src/capitalizedWordCounter.js
  src/indexEqualsValue.js
  src/indexEqualsValue.test.js
Labels: action needed

#586 Implemented isFibonacci and Added my Kata numToDescendingOrder.js
  src/isFibonacci.js
  src/numToDescendingOrder.js
  src/numToDescendingOrder.test.js
Labels: action needed

#599 Minesweeper
  src/medianOfTwoSortedArrays.js
  src/medianOfTwoSortedArrays.test.js
  src/minesweeper.js
  src/minesweeper.test.js
Labels: action needed

#653 feat: added the sleep question
  src/geometricprogression.js
  src/geometricprogression.test.js
  src/sleep.js
  src/sleep.test.js
Labels: action needed

#972 Finished moveZerosToEnd and created addMatrix
  src/addMatrix.js
  src/addMatrix.test.js
  src/moveZerosToEnd.js
Labels: action needed

#992 Implement dropRight and add isIPAddress
  src/dropRight.js
  src/isIPAddress.js
  src/isIPAddress.test.js
Labels: action needed

#966 Hacktober | Counter clock spiralized matrix
  src/pangram.js
  src/pangram.test.js
  src/spiralMatrix.js
  src/spiralMatrix.test.js
Labels: action needed
